# Generated by Django 2.2.12 on 2020-04-11 17:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import markdownx.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Will be generated automatically if left blank.', null=True, unique=True)),
                ('author', models.CharField(default='Dea Dania', help_text='Default is owner "Dea Dania".', max_length=500)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='YYYY-MM-DD HH:mm:ss')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('view_count', models.IntegerField(default=0)),
                ('comment_enabled', models.BooleanField(default=True, verbose_name='Allow comments?')),
                ('image', models.TextField(blank=True, null=True, verbose_name='Image url')),
                ('published', models.BooleanField(default=True, verbose_name='Publish now?')),
                ('featured', models.BooleanField(default=True, help_text='Include on Latest Article.', verbose_name='Feature on home page?')),
                ('summary', models.TextField(max_length=500)),
                ('content', markdownx.models.MarkdownxField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Category')),
                ('tag', models.ManyToManyField(blank=True, to='blog.Tag')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
